docker:
  image: cirrusci/flutter:latest
  as_root: true
architect:
  - rafamizes
merge:
  rebase: true
  squash: true
  script: |
    flutter clean
    flutter pub get
    flutter test --no-pub
release:
  # updates pubspec.yaml's version attribute to $tag;
  # in CHANGELOG, places section '[$tag] - YYYY-mm-dd' under [Unreleaded];
  # commits the $tag version;
  # Rultor tags the lastest commit as $tag and push the new tag to the
  # repository.
  script: |-
    sed -i "s/^\(version:\).*/\1 $tag/" pubspec.yaml
    sed -i "/\[[Uu]nreleased\]/a\\\n## [$tag] - $(date '+%F')" CHANGELOG.md
    git commit -am "version $tag"
    git checkout master
    git merge __rultor
    git checkout __rultor
