name: astronomy_picture_of_the_day
description: A Flutter project to display NASA's astronomy picture of the day.
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^5.3.3
  dio_smart_retry: ^6.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_modular: ^6.3.2
  localization: ^2.1.1
  logger: ^2.0.2+1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.2.0
  mocktail: ^1.0.1

flutter:
  assets:
    - assets/lang/

  uses-material-design: true
