name: astronomy_picture_of_the_day
description: A Flutter project to display NASA's astronomy picture of the day.
publish_to: 'none'
version: 0.1.2

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  connectivity_plus: ^5.0.2
  crypto: ^3.0.3
  dartz: ^0.10.1
  dio: ^5.3.3
  dio_smart_retry: ^6.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_modular: ^6.3.2
  internet_connection_checker_plus: ^2.1.0
  localization: ^2.1.1
  logger: ^2.0.2+1
  objectbox: ^2.3.1
  objectbox_flutter_libs: ^2.3.1
  path_provider: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  lint: ^2.2.0
  mocktail: ^1.0.1
  objectbox_generator: ^2.3.1
  test: ^1.24.9

flutter:
  assets:
    - assets/lang/

  uses-material-design: true
